name: deepl
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - cudatoolkit
    - cudatoolkit-dev
    - gcc=12
    - gxx=12
    - cmake>=3.28
    - pybind11
    - numpy
    - pip
    - graphviz